services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"   # LocalStack edge/ALL services port
      - "4571:4571"
    environment:
      - SERVICES=s3,sqs
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DEFAULT_REGION=us-east-1
    volumes:
      - ./localstack:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - localstack-network


networks:
  localstack-network:
    name: localstack-network  
    driver: bridge